from __future__ import annotations

import io
from pathlib import Path
import pytest
from PIL import Image, ImageDraw
from fastapi.testclient import TestClient
from ref_lab.api import create_app
from ref_lab.config import Settings
from ref_lab.models import Card, VisualReview

TOKEN = "test-only-access-token-not-a-live-credential-123"


def image_bytes(seed: int = 0, size: tuple[int, int] = (800, 1200)) -> bytes:
    """Synthetic test pixels, not a real photograph or a vision accuracy benchmark."""
    image = Image.new("RGB", size, (100 + seed % 80, 140, 120))
    draw = ImageDraw.Draw(image)
    draw.rectangle((size[0] // 4, size[1] // 5, size[0] * 3 // 4, size[1] * 4 // 5), fill=(190, 190 + seed % 50, 170))
    draw.text((20, 20), f"SYNTHETIC TEST FIXTURE {seed}", fill=(20, 35, 45))
    stream = io.BytesIO()
    image.save(stream, "PNG")
    return stream.getvalue()


def review_data(sha: str, **overrides) -> dict:
    data = {"asset_sha": sha, "kind": "cosplay_photo", "visible_person": True,
            "pose_readable": True, "single_image": True, "sufficiently_clear": True,
            "character_match": "exact", "observations": ["Synthetic regression evidence; not a real image assessment."],
            "critical_uncertainties": []}
    data.update(overrides)
    return data


def card_data() -> dict:
    return {"title": "回眸参考 · 合成测试数据", "intent": "验证资料卡工作流，不代表真实摄影分析。",
            "pose": {"verbal_cues": ["身体先朝那边；听到提示再舒服地回头。"],
                     "static_steps": ["先确认身体朝向，再调整视线。"], "action_directing": "看向远处，再回望。",
                     "photographer_steps": ["先确认构图，再给提示。"], "safety": "不强行扭颈。", "fallback": "减小身体背向角度。"},
            "lighting": {"visible_evidence": ["本测试图不用于判断真实光位。"], "interpretation": "测试方案，不是原作者参数。",
                         "confidence": "low", "available_gear_plan": "使用一灯方案试拍并现场调整。"},
            "retouch": {"route": "none", "steps": [], "capture_preparation": "", "background_prompt": ""}}


@pytest.fixture
def settings(tmp_path: Path):
    return Settings(tmp_path / "data", TOKEN, public_origin="http://testserver")


@pytest.fixture
def app(settings):
    return create_app(settings)


@pytest.fixture
def client(app):
    with TestClient(app) as client:
        session = client.post("/api/session", json={"token": TOKEN})
        client.headers["X-Lab-CSRF"] = session.json()["csrf"]
        yield client


@pytest.fixture
def library(app):
    return app.state.library


@pytest.fixture
def project(client):
    response = client.post("/api/projects", json={"character": "王昭君", "brief": "漫展实用参考"})
    assert response.status_code == 201
    return response.json()


def add_reference(client, project, seed=0, **values):
    asset = client.post("/api/assets", files={"file": ("fixture.png", image_bytes(seed), "image/png")})
    assert asset.status_code == 201, asset.text
    response = client.post(f"/api/projects/{project['id']}/references", json={"asset_sha": asset.json()["id"], "title": f"测试参考 {seed}", **values})
    assert response.status_code == 201, response.text
    return response.json()["reference"]


def ready_reference(client, project, seed=0):
    ref = add_reference(client, project, seed)
    source = {**ref["source"], "rights": "owned", "rights_note": "Synthetic pixels generated by this regression test", "source_confirmed": True}
    ref = client.patch(f"/api/references/{ref['id']}", json={"expected_revision": ref["revision"], "decision": "keep", "source": source}).json()
    ref = client.post(f"/api/references/{ref['id']}/review", json={"expected_revision": ref["revision"], "review": review_data(ref["asset_sha"])}).json()
    ref = client.post(f"/api/references/{ref['id']}/card", json={"expected_revision": ref["revision"], "card": card_data()}).json()
    response = client.post(f"/api/references/{ref['id']}/accept", json={"expected_revision": ref["revision"]})
    assert response.status_code == 200, response.text
    return response.json()
